# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Parking Seeker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parking Seeker
	pod 'FirebaseAnalytics'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	pod 'iOSDropDown'
	pod 'GoogleMaps'
	pod 'IQKeyboardManagerSwift'

  target 'Parking SeekerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Parking SeekerUITests' do
    # Pods for testing
  end

end
